apps/lessontests/urls.py
from django.urls import path
from .views import (LessonTestListView, LessonTestsCreateView, LessonTestDetailView, LessonTestsUpdateView, LessonTestsDeleteView, LessonTestIndividualListView, 
                    TaskTestsCreateView,
                    AjaxGetAnswerFromTask, )

app_name = 'lesson_tests'

urlpatterns = [
    path('', LessonTestListView.as_view(), name='lesson_tests_list'),
    path('individual_lesson/', LessonTestIndividualListView.as_view(), name='lesson_tests_list_individual'),

    path('lesson/create/', LessonTestsCreateView.as_view(), name='lesson_tests_create'),
    path('lesson/detail/<int:id>-<str:slug>', LessonTestDetailView.as_view(), name='lesson_tests_detail'),
    path('lesson/update/<int:pk>-<str:slug>', LessonTestsUpdateView.as_view(), name='lesson_tests_update'),
    path('lesson/delete/<int:pk>', LessonTestsDeleteView.as_view(), name='lesson_tests_delete'),

    path('task/create/', TaskTestsCreateView.as_view(), name='task_tests_create'),


    path('get_task_answer', AjaxGetAnswerFromTask.as_view(), name='get_task_answer'),
] 

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]


urlpatterns += i18n_patterns(
    path('', include('apps.books.urls', namespace='books')),
    path('users/', include('apps.users.urls', namespace = 'users')),
    path('lesson_tests/', include('apps.lessontests.urls', namespace='lesson_tests')),
    prefix_default_language = False,
)



# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include('apps.books.urls', namespace='books')),
#     path('users/', include('apps.users.urls', namespace = 'users')),
#     path('lesson_tests/', include('apps.lessontests.urls', namespace='lesson_tests')),
# ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/lessontests/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import LessonTests, TaskTests, gen_slug
from apps.users.models import ProfileUser



class LessonTestsCreateForm(forms.ModelForm):

    class Meta:
        model = LessonTests
        fields = ['title', 'permission']
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', '')
        super(LessonTestsCreateForm, self).__init__(*args, **kwargs)

    
    def save(self, commit=True):
        instance = super(LessonTestsCreateForm, self).save(commit=False)
        instance.slug = gen_slug(instance.title)       
        if commit:
            instance.save()
        return instance


class LessonTestsUpdateForm(forms.ModelForm):

    class Meta:
        model = LessonTests
        fields = ['title', 'permission']
    
    def __init__(self, *args, **kwargs):
        self.pk = kwargs.pop('pk')
        self.user = kwargs.pop('user')
        super(LessonTestsUpdateForm, self).__init__(*args, **kwargs)

    def clean_title(self):
        title = self.cleaned_data['title']
        if LessonTests.objects.exclude(pk = self.pk).filter(title = title, user = ProfileUser.objects.get(user = self.user)).exists():
            raise forms.ValidationError(_('Урок с данным названием уже существует в вашем профиле.'))
        return title



class TaskTestsCreateForm(forms.ModelForm):

    class Meta:
        model = TaskTests
        fields = '__all__'
        exclude = ['title', 'slug']

apps/lessontests/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, View
from django.db.models import Count
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse
from django.utils.translation import ugettext_lazy as _

import json

from .models import LessonTests, TaskTests, ResultTestModel, gen_slug
from .forms import LessonTestsCreateForm, LessonTestsUpdateForm, TaskTestsCreateForm
from ..users.models import ProfileUser, User

class LessonTestListView(ListView):
    model = LessonTests
    template_name='lessontests/lessontest_list.html'
    context_object_name='lessons'

    def get_queryset(self):
        return LessonTests.all_objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(LessonTestListView, self).get_context_data(*args, **kwargs)
        context['tasks'] = LessonTests.all_objects.annotate(count = Count('tasktests')).values('title', 'count')
        return context


class LessonTestIndividualListView(ListView):
    model = LessonTests
    template_name='lessontests/lessontest_list_individ.html'
    context_object_name='lessons'

    def get_queryset(self):
        return []
        # return LessonTests.individual_objects.all()
    
    def get_context_data(self, *args, **kwargs):
        context = super(LessonTestIndividualListView, self).get_context_data(*args, **kwargs)
        context['tasks'] = LessonTests.individual_objects.annotate(count = Count('tasktests')).values('title', 'count')
        return context


class LessonTestsCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = LessonTests
    template_name = 'lessontests/lessontest_create.html'
    success_message = 'Success: Lesson was created.' 
    success_url = reverse_lazy('lesson_tests:lesson_tests_list')
    form_class = LessonTestsCreateForm
    login_url = reverse_lazy('users:login')
    

    def test_func(self):
        if self.request.user.is_superuser or ProfileUser.objects.get(user = self.request.user).get_person_display() == 'Teacher':
            return True
        return False

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(LessonTestsCreateView, self).get_form_kwargs(*args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.user = ProfileUser.objects.get(user = self.request.user)
        form.instance.slug = gen_slug(form.instance.title)
        return super().form_valid(form)


class LessonTestsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = LessonTestsUpdateForm
    model = LessonTests
    context_object_name = 'lesson'
    template_name = 'lessontests/lessontests_update.html'
    login_url = reverse_lazy('users:login')

    # owner or superuser
    def test_func(self):
        if self.request.user.is_superuser or self.get_object().owner.user == self.request.user:
            return True
        return False

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(LessonTestsUpdateView, self).get_form_kwargs(*args, **kwargs)
        kwargs['user'] = self.request.user
        kwargs['pk'] = self.kwargs['pk']
        return kwargs
    
    def form_valid(self, form):
        form.instance.slug = gen_slug(form.instance.title)
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return self.get_object().get_absolute_url()


class LessonTestsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = LessonTests
    template_name = 'lessontests/lessontest_delete.html'
    context_object_name = 'lesson'
    login_url = reverse_lazy('users:login')

    # owner or superuser
    def test_func(self):
        if self.request.user.is_superuser or self.get_object().owner.user == self.request.user:
            return True
        return False

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, 'Вы удалили урок. Поздравляю.')
        return reverse('lesson_tests:lesson_tests_list')



class LessonTestDetailView(DetailView):
    model = LessonTests
    template_name = 'lessontests/lessontests_detail.html'
    context_object_name='lesson'

    def test_func(self):
        if self.request.user.is_superuser or ProfileUser.objects.get(user = self.request.user).get_person_display() == 'Teacher':
            return True
        return False

    def get_context_data(self, *args, **kwargs):
        context = super(LessonTestDetailView, self).get_context_data(*args, **kwargs)
        context['tasks'] = TaskTests.objects.filter(lesson = self.get_object()).order_by('position_in')
        return context



def get_clear_result(data, answer):
    wrong, correct = 0, 0

    for i in data:
        if 'active' in i['result']:
            i['result'] = answer

    for i in data:
        if i['result'] == 'wrong':
            wrong +=1
        else:
            correct +=1

    return wrong, correct, data


class AjaxGetAnswerFromTask(View):

    def get(self, *args, **kwargs):
        answers = self.request.GET.get('answers')
        lesson_id = self.request.GET.get('lesson_id')
        position_in = self.request.GET.get('position_in')
        username = self.request.GET.get('username')

        result_content = self.request.GET.getlist('result_content[]', [])
        result_content = [json.loads(item) for item in result_content]

        wrong, correct, statistic = 0, 0, []     ############  дабы не было ошибок во вьюхе
        

        clear_answer = answers.replace('"','').replace('[','').replace(']','').replace(',','')
        right_answer = TaskTests.objects.get(lesson__id = lesson_id, position_in = position_in).right_answer

        if len(clear_answer) > len(right_answer):
            result = 'wrong'
        elif clear_answer[0] != right_answer and len(right_answer) == 1: 
            result = 'wrong'
        else:
            result = 'correct'

        # TODO - если result_content == 0, значит это последний вопрос и нужно опправлять статистику\
        # сохраняем только залогиненные пользователи
        if len(result_content) > 0:
            wrong, correct, clear_result = get_clear_result(result_content, result)
            if username != 'anonym' and username:
                ResultTestModel.objects.create(
                    lesson = get_object_or_404(LessonTests, pk = lesson_id),
                    user = get_object_or_404(ProfileUser, user = get_object_or_404(User, email = username)),
                    result = clear_result
                )  

                # prepare statistics
                data = ResultTestModel.objects.filter(
                    lesson = get_object_or_404(LessonTests, pk = lesson_id),
                    user = get_object_or_404(ProfileUser, user = get_object_or_404(User, email = username))
                ).values_list('created', 'result')

                timeperiod, percentage = [], []
                for i in data:
                    wrong = i[1].count('wrong')
                    correct = i[1].count('correct')
                    res = round((correct / (correct+wrong)) * 100)
                    percentage.append(res)

                    period = i[0].strftime('%d/%m/%Y')
                    timeperiod.append(period)
                statistic.append({
                    'period':timeperiod if len(timeperiod) <=10 else timeperiod[-10:], 
                    'percentage':percentage if len(percentage) <=10 else percentage[-10:]
                })

        your_result = _('your result')
        corr_res = _('corr result')
        wrong_res = _('wrong result')  
        history_result = _('History of results (last 10 results):')          
        perc_correct = _('Percent of correct results.')

        data = {
            'status': result,
            'wrong': wrong,
            'correct': correct,
            'statistic': statistic,
            'your_result': your_result, 'corr_res': corr_res, 'wrong_res': wrong_res, 'history_result':history_result, 'perc_correct':perc_correct,
        }
        return JsonResponse(data, safe=False)


class TaskTestsCreateView(CreateView):
    model = TaskTests
    form_class = TaskTestsCreateForm
    template_name = 'lessontests/tasktest_create.html'

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, 'Вы создали задание. Поздравляю.')
        return reverse('lesson_tests:lesson_tests_list')

templates/lessontests/lessontest_create.html
{% extends 'base.html' %}
{% load static i18n %}
{% load widget_tweaks %}


{% block title %}
    {% trans "Create lesson" %} - {{ block.super }}
{% endblock %}


{% block content %}

<form action="" class="login-form" method="POST">
    {% csrf_token %}
    
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger mt-2">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    </div>

    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        <div class="{% if field.errors %} invalid{% endif %}">
        {% for error in field.errors %}
            <p class="help-block">
                <div class="alert alert-danger mt-2">
                    <strong>{{ error }}</strong>
                </div>
            </p>
        {% endfor %}
        </div>
    </div>
    {% endfor %}

    <input type="submit" value='{% trans "Create lesson" %}' class='signup__btn'>
    <a href="{% url 'lesson_tests:lesson_tests_list' %}">{% trans "cancel" %}</a>
</form>

{% endblock %}


{% block extra_js %}



{% endblock %}

templates/lessontests/lessontest_delete.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}
    {% trans "Delete lesson" %} - {{ block.super }}
{% endblock %}


{% block content %}

<form action="" class="login-form" method="POST">
    {% csrf_token %}
    <p>{% trans "Are you sure want delete the lesson" %} "{{ lesson.title }}"?</p>
    <input type="submit" value='{% trans "Confirm" %}'>
</form>

{% endblock %}

templates/lessontests/lessontest_list.html
{% extends 'base.html' %}
{% load static i18n %}


{% block title %}
    {% trans "Lessons" %} - {{ block.super }}
{% endblock %}



{% block adminpanel %}
<div class="admin-panel">
    <a href="{% url 'lesson_tests:lesson_tests_create' %}" class="btn btn-primary">{% trans "Create lesson" %}</a>
</div>
{% endblock %}



{% block content %}

<h2 class='lesson-title'>{% trans "List of all lessons." %}</h2>
<ul class='lesson-list'>
    {% for lesson in lessons %}
        <li class='lesson-list__item'><a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}
            {% for task in tasks %}
                {% if task.title == lesson.title %}
                    ({{ task.count }})
                {% endif %}
            {% endfor %}
        </a> by {{ lesson.owner }}</li>
    {% empty %}
        <li>{% trans "Sorry, we do not have any lessons." %}</li>
    {% endfor %}
</ul>

{% endblock %}

templates/lessontests/lessontest_list_individ.html
{% extends 'base.html' %}
{% load static i18n %}
{% load lessontags %}


{% block title %}
    {% trans "Individual lessons" %} - {{ block.super }}
{% endblock %}


{% block adminpanel %}
<div class="admin-panel">
    <a href="{% url 'lesson_tests:lesson_tests_create' %}" class="btn btn-primary">{% trans "Create lesson" %}</a>
</div>
{% endblock %}


{% block content %}


{% display_individ_lesson request.user as lessons %}
<h2 class='lesson-title'>{% trans "List of all lessons." %}</h2>
<ul class='lesson-list'>
    {% for lesson in lessons %}
        <li class='lesson-list__item'><a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}
            {% for task in tasks %}
                {% if task.title == lesson.title %}
                    ({{ task.count }})
                {% endif %}
            {% endfor %}
        </a> by {{ lesson.owner }}</li>
    {% empty %}
        <li>{% trans "Sorry, we do not have any lessons." %}</li>
    {% endfor %}
</ul>


{% endblock %}

templates/lessontests/lessontests_detail.html
{% extends 'base.html' %}
{% load static i18n %}
{% load widget_tweaks %}


{% block title %}   
    {{ lesson }} - {{ block.super }}
{% endblock %}


{% block adminpanel %}
<div class="admin-panel">
    <a href="{% url 'lesson_tests:lesson_tests_update' lesson.id lesson.slug %}" class="btn btn-primary">{% trans "Update lesson" %}</a>
    <a href="{% url 'lesson_tests:lesson_tests_delete' lesson.pk %}" class="btn btn-danger">{% trans "Delete lesson" %}</a>
    <a href="{% url 'lesson_tests:task_tests_create' %}" class="btn btn-success">{% trans "Create lesson" %}</a>
</div>
{% endblock %}



{% block content %}


<div class="general_section">
    <div class="general_section-sidebar">
        {% for task in tasks %}
            <p class='general_section-sidebar--counter sidebar-btn {% if forloop.counter == 1 %}active{% endif %} empty' data-id="{{ forloop.counter }}" onclick="clickSidebarBtn(event)">
                <span class='general_section-sidebar--counter_span'>{{ forloop.counter }}</span>
            </p>
        {% endfor %}
    </div>
    
    <div class="general_section-content" data-id='{{ lesson.id }}'>
        {% for task in tasks %}
            <div class="general_section-content-item {% if forloop.counter == 1 %}active{% endif %}" id='question-{{ forloop.counter }}'>
                <h4 class="general_section-content-item--title">{{ task.title }}
                    <button type="button" class="delete-task btn btn-sm btn-danger" data-id="" data-toggle="tooltip" data-placement="bottom" title='{% trans "Delete task" %}'>
                        <span class="fa fa-trash"></span>
                    </button>
                    <button type="button" class="update-task btn btn-sm btn-warning" data-id="" data-toggle="tooltip" data-placement="bottom" title='{% trans "Update task" %}'>
                        <span class="fa fa-edit"></span>
                    </button>
                </h4>
                
                <div class="general_section-content-item--question">
                    {% if task.type_question == "choose" %}
                    <p class='task-question'>{{ task.question }}</p>

                    <div class='question-checkboxes' style='display: block;'>
                        <div>
                            <input type="checkbox" id="qs-a" name="qs-a" class='question-checkboxes--input' onclick="addCheckedToCheckbox(event)">
                            <label for="qs-a" class='question-checkboxes--label'>{{ task.a }}</label>
                        </div>
                        <div>
                            <input type="checkbox" id="qs-b" name="qs-b" class='question-checkboxes--input' onclick="addCheckedToCheckbox(event)">
                            <label for="qs-b" class='question-checkboxes--label'>{{ task.b }}</label>
                        </div>
                        <div>
                            <input type="checkbox" id="qs-c" name="qs-c" class='question-checkboxes--input' onclick="addCheckedToCheckbox(event)">
                            <label for="qs-c" class='question-checkboxes--label'>{{ task.c }}</label>
                        </div>
                        <div>
                            <input type="checkbox" id="qs-d" name="qs-d" class='question-checkboxes--input' onclick="addCheckedToCheckbox(event)">
                            <label for="qs-d" class='question-checkboxes--label'>{{ task.d }}</label>
                        </div>
                    </div>
                    {% endif %}
                </div>
                <div class="general_section-content-item--footer">
                    <button type="button" class="btn btn-send header_btn" id='btn-send' data-id='confirm_btn-{{ forloop.counter }}' data-href='{% url "lesson_tests:get_task_answer" %}' onclick='clickConfirmAnswer(event)'>{% trans "Send" %}</button>
                </div>
            </div>
        {% endfor %}
    </div>
</div>




{% endblock %}


{% block extra_js %}

<script src='{% static "js/lessontests/lesson_detail.js" %}'></script>

{% endblock %}	

templates/lessontests/lessontests_update.html
{% extends 'base.html' %}
{% load static i18n %}
{% load widget_tweaks %}


{% block title %}
    {% trans "Update lesson" %} ({{lesson}}) - {{ block.super }}
{% endblock %}


{% block content %}

<form action="" class="login-form" method="POST">
    {% csrf_token %}
    
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger mt-2">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    </div>

    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        <div class="{% if field.errors %} invalid{% endif %}">
        {% for error in field.errors %}
            <p class="help-block">
                <div class="alert alert-danger mt-2">
                    <strong>{{ error }}</strong>
                </div>
            </p>
        {% endfor %}
        </div>
    </div>
    {% endfor %}

    <input type="submit" value='{% trans "Update lesson" %}' class='signup__btn'>
    <a href="{% url 'lesson_tests:lesson_tests_list' %}">{% trans "cancel" %}</a>
</form>

{% endblock %}


{% block extra_js %}



{% endblock %}

templates/lessontests/tasktest_create.html
{% extends 'base.html' %}
{% load static i18n %}
{% load widget_tweaks %}


{% block title %}
    {% trans "Create lesson" %} - {{ block.super }}
{% endblock %}


{% block content %}

<form action="" class="login-form" method="POST">
    {% csrf_token %}
    
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger mt-2">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    </div>

    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        <div class="{% if field.errors %} invalid{% endif %}">
        {% for error in field.errors %}
            <p class="help-block">
                <div class="alert alert-danger mt-2">
                    <strong>{{ error }}</strong>
                </div>
            </p>
        {% endfor %}
        </div>
    </div>
    {% endfor %}

    <input type="submit" value='{% trans "Create lesson" %}' class='signup__btn'>
    <a href="{% url 'lesson_tests:lesson_tests_list' %}">{% trans "cancel" %}</a>
</form>

{% endblock %}


{% block extra_js %}



{% endblock %}