apps/lessontests/urls.py
from django.urls import path
from .views import (LessonTestListView, LessonTestsCreateView, LessonTestDetailView, LessonTestsUpdateView, LessonTestsDeleteView, LessonTestIndividualListView, 
                    TaskTestsCreateView,
                    AjaxGetAnswerFromTask, )

app_name = 'lesson_tests'

urlpatterns = [
    path('', LessonTestListView.as_view(), name='lesson_tests_list'),
    path('individual_lesson/', LessonTestIndividualListView.as_view(), name='lesson_tests_list_individual'),

    path('lesson/create/', LessonTestsCreateView.as_view(), name='lesson_tests_create'),
    path('lesson/detail/<int:id>-<str:slug>', LessonTestDetailView.as_view(), name='lesson_tests_detail'),
    path('lesson/update/<int:pk>-<str:slug>', LessonTestsUpdateView.as_view(), name='lesson_tests_update'),
    path('lesson/delete/<int:pk>', LessonTestsDeleteView.as_view(), name='lesson_tests_delete'),

    path('task/create/', TaskTestsCreateView.as_view(), name='task_tests_create'),


    path('get_task_answer', AjaxGetAnswerFromTask.as_view(), name='get_task_answer'),
] 

apps/users/urls.py
from django.urls import path, reverse_lazy
from .views import (CustomLoginView, CustomLogoutView, CustomRegistrationView, AjaxCreationUserView, AjaxLoginUserView,
                    AjaxModalLoginUserView, )

app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(next_page = reverse_lazy('books:base_view')), name='logout'),
    path('registration/', CustomRegistrationView.as_view(), name='registration'),

    path('custom_creation_view', AjaxCreationUserView.as_view(), name='custom_creation_view'),
    path('custom_login_view', AjaxLoginUserView.as_view(), name = 'custom_login_view'),

    path('custom_modal_login_view', AjaxModalLoginUserView.as_view(), name = 'custom_modal_login_view'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]


urlpatterns += i18n_patterns(
    path('', include('apps.books.urls', namespace='books')),
    path('users/', include('apps.users.urls', namespace = 'users')),
    path('lesson_tests/', include('apps.lessontests.urls', namespace='lesson_tests')),
    prefix_default_language = False,
)



# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include('apps.books.urls', namespace='books')),
#     path('users/', include('apps.users.urls', namespace = 'users')),
#     path('lesson_tests/', include('apps.lessontests.urls', namespace='lesson_tests')),
# ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
{% load static i18n %}
{% load i18n_switcher %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
    <title>
        {% block title %}Create English Books{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" rel="stylesheet"  type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>


<nav class="navbar navbar-expand-md">
    <a class="navbar-brand" href="/">LOGO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">{% trans "books" %}</a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="#">Интерактивное чтиво</a>
            </li> -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'lesson_tests:lesson_tests_list' %}">{% trans "tests" %}</a>
            </li>  
            <li class="nav-item">
                <a class="nav-link" href="{% url 'lesson_tests:lesson_tests_list_individual' %}">{% trans "individual tests" %}</a>
            </li>  
        </ul>

        <ul class="navbar-nav float-right reg-section">  

            <div class="lang_panel">
                <a href="{{ request|switch_i18n:'en' }}">
                    <img src="{% static 'img/eng.png' %}" alt="" class='lang_panel-img'>EN
                </a>
                <a href="{{ request|switch_i18n:'ru' }}">
                    <img src="{% static 'img/ru.png' %}" alt="" class='lang_panel-img'>RU
                </a>
            </div>   

            {% if not user.is_authenticated %}
            <li class="nav-item">
                <a href="{% url 'users:registration' %}" class="btn header_btn reg_btn">{% trans "reg" %}</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'users:custom_modal_login_view' %}" class="btn header_btn signin_modal">{% trans "log in" %}</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="#" class="btn header_btn profile_btn" data-id="{{ request.user }}">{% trans "profile" %}</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'users:logout' %}" class="btn header_btn logout_btn">{% trans "log out" %}</a>
            </li>   
            {% endif %} 
        </ul>
    </div>  
</nav> 

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <b>{{ message }}</b>
        </div>
    {% endfor %}
{% endif %}


{% block adminpanel %}{% endblock %}

{% block content %}{% endblock %}




<footer class="footer">
    <div class="footer__logo-box">

        <!-- <picture class="footer_logo">
            <source srcset="{% static 'img/logo-green-small-1x.png' %} 1x, {% static 'img/logo-green-small-2x.png' %} 2x" 
                    media="(max-width: 37.5em)">
            <img srcset="{% static 'img/logo-green-1x.png' %} 1x, {% static 'img/logo-green-2x.png' %} 2x" alt="" src="{% static 'img/logo-green-2x.png' %}">
        </picture> -->
    </div>
    <div class="row">
        <div class="col-1-of-2 col-1-of-2-clear">
            <div class="footer__navigation">
                <ul class="footer__list">
                    <li class="footer__item"><a href="#" class="footer__link">{% trans "books" %}</a></li>
                    <!-- <li class="footer__item"><a href="#" class="footer__link">Интерактивное чтиво</a></li> -->
                    <li class="footer__item rm-margin-right"><a href="{% url 'lesson_tests:lesson_tests_list' %}" class="footer__link">{% trans "tests" %}</a></li>
                </ul>
            </div>
        </div>
        <div class="col-1-of-2">
            <div class="footer__copyright">
                Build by <a href="#" class="footer__link">delme</a> for <a href="#" class="footer__link">English study programm</a>. <br>Copyright &copy;2019 by amyard.
            </div>
        </div>
    </div>
</footer>



<div class="modal fade" id="modal-general">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>


{% block js %}
<script src="{% static 'js/lodash.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script src='{% static "js/users/login_modal.js" %}'></script>

<script type="text/javascript">
    $(function () {
      // Hide message
      $(".alert").fadeTo(3000, 500).slideUp(500, function(){
        $(".alert").slideUp(500);
      });
    });
</script>



{% endblock %}


{% block extra_js %}{% endblock %}
</body>
</html>