apps/users/urls.py
from django.urls import path, reverse_lazy
from .views import (CustomLoginView, CustomLogoutView, CustomRegistrationView, AjaxCreationUserView, AjaxLoginUserView,
                    AjaxModalLoginUserView, )

app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(next_page = reverse_lazy('books:base_view')), name='logout'),
    path('registration/', CustomRegistrationView.as_view(), name='registration'),

    path('custom_creation_view', AjaxCreationUserView.as_view(), name='custom_creation_view'),
    path('custom_login_view', AjaxLoginUserView.as_view(), name = 'custom_login_view'),

    path('custom_modal_login_view', AjaxModalLoginUserView.as_view(), name = 'custom_modal_login_view'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]


urlpatterns += i18n_patterns(
    path('', include('apps.books.urls', namespace='books')),
    path('users/', include('apps.users.urls', namespace = 'users')),
    path('lesson_tests/', include('apps.lessontests.urls', namespace='lesson_tests')),
    prefix_default_language = False,
)



# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include('apps.books.urls', namespace='books')),
#     path('users/', include('apps.users.urls', namespace = 'users')),
#     path('lesson_tests/', include('apps.lessontests.urls', namespace='lesson_tests')),
# ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/users/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import PermissionsMixin


USERNAME_REGEX = '^[a-zA-Z0-9.+-]*$'


class UserManager(BaseUserManager):

    def _create_user(self, email, password, **extra_fields):
        # if not username:
        #     raise ValueError('The username must be set')
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_admin', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        if extra_fields.get('is_admin') is not True:
            raise ValueError(_('Superuser must have is_admin=True.'))
        return self._create_user(email, password, **extra_fields)



class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=75, unique=True,
                            validators=[RegexValidator(regex=USERNAME_REGEX,
                                                        message=_('Username must be alphanumeric or contain numbers'),
                                                        code='invalid_username')]
                            )
    email = models.EmailField(max_length=255, unique=True)

    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')
        ordering = ('-id',)

    def __str__(self):
        return self.email

    def get_short_name(self):
        return self.email


    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True




class ProfileUser(models.Model):
    Persona = (
        ('T', 'Teacher'),
        ('S', 'Student'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name=_('User'))
    person = models.CharField(max_length=7, choices=Persona, default='Student')

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = _('Profile User')
        verbose_name_plural = _('Profile Users')
        ordering = ['-id']

apps/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.core.validators import validate_email
from django.utils.translation import ugettext_lazy as _


User = get_user_model()


class CustomAuthenticationForm(AuthenticationForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['password']

    def clean_username(self):
        email = self.cleaned_data['username']
        if '@' not in email:
            raise forms.ValidationError(_('Missed the @ symbol in the email address.'))
        if '.' not in email:
            raise forms.ValidationError(_('Missed the . symbol in the email address.'))
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(_('User with such email doesn\'t exists.'))
        try:
            mt = validate_email(email)
        except:
            raise forms.ValidationError(_('Incorrect email.'))
        return email

    def clean_password(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data['password']
        user = User.objects.filter(email=email)
        if not user:
            raise forms.ValidationError(_('Invalid password for this user.'))
        elif not User.objects.get(email=email).check_password(password):
            raise forms.ValidationError(_('Invalid password.'))
        return password



class CustomUserCreationForm(forms.ModelForm):
    CHOICES = (
        ('T', 'Teacher'),
        ('S', 'Student'),
    )

    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':_('Enter your username')}))
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':_('Enter an email')}))
    
    select = forms.ChoiceField(label='Person', widget=forms.Select, choices=CHOICES)
    
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':_('Enter password')}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':_('Repeat your password again')}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(_('User with this name already exist.'))
        return username


    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError(_('Your passwords don\'t match.'))
        return password2


    def clean_email(self):
        email = self.cleaned_data['email']
        if '@' not in email:
            raise forms.ValidationError(_('Missed the @ symbol in the email address.'))
        if '.' not in email:
            raise forms.ValidationError(_('Missed the . symbol in the email address.'))
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(_('User with such email already exists.'))
        try:
            mt = validate_email(email)
        except:
            raise forms.ValidationError(_('Incorrect email.'))
        return email

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.is_active = True
            user.save()
        return user

apps/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import View
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib import messages
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _

from .forms import CustomAuthenticationForm, CustomUserCreationForm
from .models import ProfileUser

User = get_user_model()


class CustomLogoutView(LogoutView):
    def get_next_page(self):
        next_page = super(CustomLogoutView, self).get_next_page()
        messages.add_message(self.request, messages.SUCCESS, _('Success: You successfully log out!'))
        return next_page


class CustomLoginView(SuccessMessageMixin, LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'users/login.html'
    success_message = _('Success: You were successfully logged in.')
    success_url = reverse_lazy('books:base_view')


class CustomRegistrationView(View):
    template_name = 'users/registration.html'
    form = CustomUserCreationForm
    message = _('Your account has been created! You are now able to log in.')

    def get(self, request, *args, **kwargs):
        context = {'form':self.form}
        return render(self.request, self.template_name, context)

    def post(self, request, *args,**kwargs):
        form = self.form(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            ProfileUser.objects.create(
                user = user,
                person = form.cleaned_data['select']
            )
            messages.add_message(self.request, messages.SUCCESS, self.message)
            return HttpResponseRedirect('/')

        form = self.form(request.POST)
        context = {'form':form}
        return render(self.request, self.template_name, context)


class AjaxCreationUserView(View):

    def post(self, request, *args, **kwargs):
        username = self.request.POST.get('username')
        email = self.request.POST.get('email')
        password = self.request.POST.get('password')
        person = self.request.POST.get('person')

        error_list = []
        success_list = ''

        if User.objects.filter(username=username).exists():
            error_list.append({'selector': 'id_username', 'value': _('User with this name already exist.')})
        if User.objects.filter(email=email).exists():
            error_list.append({'selector': 'id_email', 'value': _('User with this email already exist.')})
        else:
            user = User.objects.create(username=username, email=email)
            user.set_password(password)
            user.save()

            prof = ProfileUser.objects.create(user = user)
            prof.person = person[0]
            prof.save()
            success_list = 'ok'

        data = {
            'errors': error_list,
            'success': success_list
        }
        return JsonResponse(data, safe=False)


from django.template.loader import render_to_string
class AjaxModalLoginUserView(View):
    def get(self, request, *args, **kwargs):
        template_name = 'users/login_modal.html'
        form = CustomAuthenticationForm()
        context = {'form': form}

        html_form = render_to_string(template_name, context, request=self.request)
        return JsonResponse({'html_form': html_form})


class AjaxLoginUserView(View):

    def post(self, request, *args, **kwargs):
        email = self.request.POST.get('username')
        password = self.request.POST.get('password')

        error_list = []
        success_list = ''

        if not User.objects.filter(email=email).exists():
            error_list.append({'selector': 'id_username', 'value': _('Пользователь такого не существует.')})
        if not User.objects.get(email=email).check_password(password):
            error_list.append({'selector': 'id_password', 'value': _('Пароль не соответствует.')})
        else:
            user = authenticate(username=email, password=password)
            login(self.request, user)
            success_list = 'ok'
        
        success_message = _('Success: You were successfully logged in.')

        data = {
            'errors': error_list,
            'success': success_list,
            'success_message': success_message
        }
        return JsonResponse(data, safe=False)

templates/users/login.html
{% extends 'base.html' %}
{% load static i18n %}
{% load widget_tweaks %}


{% block title %}
    {% trans "log in" %} - {{ block.super }}
{% endblock %}


{% block content %}

<form action="" class="login-form" method="POST">
    {% csrf_token %}
    
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger mt-2">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    </div>

    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        <div class="{% if field.errors %} invalid{% endif %}">
        {% for error in field.errors %}
            <p class="help-block">
                <div class="alert alert-danger mt-2">
                    <strong>{{ error }}</strong>
                </div>
            </p>
        {% endfor %}
        </div>
    </div>
    {% endfor %}

    <input type="submit" value="{% trans 'log in' %}" class='signup__btn' data-id='{% url "users:custom_login_view" %}'>
    <a href="{% url 'books:base_view' %}">{% trans "cancel" %}</a>
</form>

{% endblock %}


{% block extra_js %}

    <script src='{% static "js/users/login.js" %}'></script>

{% endblock %}

templates/users/login_modal.html
{% load widget_tweaks %}
{% load static i18n %}


<form method="post">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">{% trans "login" %}</h4>
  </div>
  <div class="modal-body">
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger mt-2">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    </div>

    {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% render_field field class="form-control" %}
            <div class="{% if field.errors %} invalid{% endif %}">
            {% for error in field.errors %}
                <p class="help-block">
                    <div class="alert alert-danger mt-2">
                        <strong>{{ error }}</strong>
                    </div>
                </p>
            {% endfor %}
            </div>
        </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "close" %}</button>
    <button type="submit" class="btn btn-primary signup__btn" data-id='{% url "users:custom_login_view" %}'>{% trans "log in" %}</button>
  </div>
</form>

templates/users/registration.html
{% extends 'base.html' %}
{% load static i18n %}
{% load widget_tweaks %}

{% block title %}
    {% trans "reg" %} - {{ block.super }}
{% endblock %}


{% block content %}

<div class="bg-video">
    <video class="bg-video__content" autoplay muted loop>
        <!--   can download video from "coverr.co"   -->
        <source src="{% static 'video/video_book.mp4' %}" type="video/mp4">
        <source src="{% static 'video/video_book.webm' %}" type="video/webm">
        {% trans "Your browser is not supported!" %}    
    </video>
</div>


<form action="" class="login-form reg-form" method="POST">
    {% csrf_token %}
    
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger mt-2">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    </div>

    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        <div class="{% if field.errors %} invalid{% endif %}">
        {% for error in field.errors %}
            <p class="help-block">
                <div class="alert alert-danger mt-2">
                    <strong>{{ error }}</strong>
                </div>
            </p>
        {% endfor %}
        </div>
    </div>
    {% endfor %}

    <input type="submit" value="{% trans 'reg' %}" class='signup__btn' data-id='{% url "users:custom_creation_view" %}'>
    <a href="{% url 'books:base_view' %}">{% trans "cancel" %}</a>
</form>

<!-- The Modal -->
<div id="myModal" class="modal">
    <div class="modal-content">
        <div class="modal-header">
            <span class="close">&times;</span>
        </div>
        <div class="modal-body">
            <p>{% trans "Спасибо что зарегестрировались. Вы будете перенаправлену на главную страницу автоматически через" %} <span id='modal-timer'>5</span> {% trans "сек" %}.</p>
        </div>
    </div>
</div>



{% endblock %}


{% block extra_js %}

    <script src='{% static "js/users/sign.js" %}'></script>

{% endblock %}